apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: conduwuit
spec:
  values:
    config:
      global:
        oauth:
          oidc:
            additional_scopes:
              - profile
              - email
              - groups
            prompt_for_localpart: false
            profile_key_import_mode: on_registration
            profile_key_map:
              displayname: name
              avatar_url: picture
    controllers:
      main:
        containers:
          main:
            envFrom:
              - secretRef:
                  name: conduwuit-oidc-credentials
