apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  values:
    grafana.ini:
      auth:
        disable_login_form: true
      auth.generic_oauth:
        enabled: true
        name: Pocket ID
        scopes: openid profile email groups
        use_pkce: true
        role_attribute_path: "contains(groups[*], 'grafana-admin') && 'Admin' || 'Viewer'"
        allow_assign_grafana_admin: true
    # TODO: use json patch here
    envFromSecrets:
      - name: grafana-oidc-credentials
