apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: vikunja
spec:
  name: Vikunja
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vikunja.svg
  secret:
    name: vikunja-oidc-credentials
  launchUrl: https://vikunja.${CLUSTER_DOMAIN}
  callbackUrls:
    - https://vikunja.${CLUSTER_DOMAIN}/auth/openid/pocketid
  allowedUserGroups:
    - name: vikunja
