apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/grafana/controller
components:
  - ../../../base/grafana/controller/components/oidc
patches:
  - path: patches/trust.yaml
